spring:
  application:
    name: Welcome-Service
  boot:
    admin:
      client:
        url: http://localhost:1111/

server:
  port: 8081
  
#eureka:
#  client:
 #   service-url:
  #    defaultZone: http://localhost:8761/eureka/
  
  
  # if eureka server port number 8761 then no need to write above url property
  
management:
  endpoints:
    web:
      exposure:
        include: '*'